# Generated by Django 6.1 on 2026-08-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritejob',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='jobs.joboffer'),
        ),
        migrations.AddConstraint(
            model_name='favoritejob',
            constraint=models.UniqueConstraint(fields=('candidate', 'job_offer'), name='unique_candidate_favorite_job'),
        ),
    ]
