# Generated by Django 6.1 on 2026-08-10 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidateprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
