# Generated by Django 6.0.3 on 2026-09-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_candidateprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/recruiters/'),
        ),
    ]
