# Generated by Django 6.1 on 2026-08-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_candidateprofile_cv'),
        ('companies', '0002_alter_company_options_company_is_active'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_offers', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('PART_TIME', 'Part Time')], max_length=30),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('ENTRY', 'Entry Level'), ('JUNIOR', 'Junior'), ('MID', 'Mid Level'), ('SENIOR', 'Senior')], max_length=20),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='joboffer',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_max__gte', models.F('salary_min')), _connector='OR'), name='salary_max_gte_salary_min'),
        ),
    ]
